language: ruby
rvm:
  - 1.9.3
  - 2.1.0
  - ruby-head
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec --require spec_helper --color --format documentation spec
